networks:
    openmusic:
        name: openmusic

services:
    app:
        container_name: openmusic-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - postgres
        networks:
            - openmusic

    postgres:
        container_name: openmusic-db
        image: postgres:17.5
        restart: always
        volumes:
            - ./docker/postgres/data:/var/lib/postgres/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - openmusic

    web:
        container_name: openmusic-web
        image: nginx:stable-alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - openmusic
